name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cada vez que haya cambios en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos un contenedor de Ubuntu para la acción

    steps:
      # Paso 1: Check-out el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Instalar Node.js (si lo necesitas, por ejemplo, si usas Astro o cualquier framework)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Puedes ajustar la versión según tus necesidades

      # Paso 3: Instalar dependencias (si usas npm)
      - name: Install dependencies
        run: npm install  # Si usas otro gestor de dependencias, ajusta este paso

      # Paso 4: Construir el proyecto
      - name: Build the project
        run: npm run build  # Usa este comando si tu proyecto requiere compilación

      # Paso 5: Desplegar los archivos a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Especifica la carpeta que quieres desplegar
